<form action="{{ route('register.doctor.store') }}" method="POST" class="space-y-8">
    @csrf
    <section class="space-y-5 border-b border-surface-variant pb-8">
        <div class="flex items-start gap-3"><span class="material-symbols-outlined mt-0.5 text-primary">person</span><div><h3 class="font-titre-sm text-titre-sm text-on-surface">Identité professionnelle</h3><p class="mt-1 font-corps-sm text-corps-sm text-on-surface-variant">Présentez votre profil de professionnel de santé.</p></div></div>
        <div class="grid grid-cols-1 gap-gouttiere sm:grid-cols-2">
            <div><label for="doctorTitle" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Civilité <span class="text-error">*</span></label><select id="doctorTitle" name="title" required class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"><option value="Dr." @selected(old('title', 'Dr.') === 'Dr.')>Dr.</option><option value="Pr." @selected(old('title') === 'Pr.')>Pr.</option><option value="M." @selected(old('title') === 'M.')>M.</option><option value="Mme" @selected(old('title') === 'Mme')>Mme</option></select></div>
            <div><label for="doctorEstablishment" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Établissement <span class="text-error">*</span></label><select id="doctorEstablishment" name="id_etablissement" required class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"><option value="">Sélectionner votre établissement</option>@foreach ($etablissements as $etablissement)<option value="{{ $etablissement->id_etablissement }}" @selected(old('id_etablissement') === $etablissement->id_etablissement)>{{ $etablissement->nom_etablissement }}</option>@endforeach</select></div>
            <div><label for="doctorFirstName" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Prénom <span class="text-error">*</span></label><input id="doctorFirstName" name="first_name" required maxlength="100" value="{{ old('first_name') }}" class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"></div>
            <div><label for="doctorLastName" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Nom <span class="text-error">*</span></label><input id="doctorLastName" name="last_name" required maxlength="100" value="{{ old('last_name') }}" class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"></div>
        </div>
    </section>
    <section class="space-y-5 border-b border-surface-variant pb-8">
        <div class="flex items-start gap-3"><span class="material-symbols-outlined mt-0.5 text-primary">medical_services</span><div><h3 class="font-titre-sm text-titre-sm text-on-surface">Expertise professionnelle</h3><p class="mt-1 font-corps-sm text-corps-sm text-on-surface-variant">Ajoutez votre spécialité et votre identifiant professionnel.</p></div></div>
        <div class="grid grid-cols-1 gap-gouttiere sm:grid-cols-2"><div><label for="doctorSpecialty" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Spécialité <span class="text-error">*</span></label><select id="doctorSpecialty" name="specialty" required class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"><option value="Médecine Générale" @selected(old('specialty') === 'Médecine Générale')>Médecine générale</option><option value="Cardiologie" @selected(old('specialty') === 'Cardiologie')>Cardiologie</option><option value="Dermatologie" @selected(old('specialty') === 'Dermatologie')>Dermatologie</option><option value="Pédiatrie" @selected(old('specialty') === 'Pédiatrie')>Pédiatrie</option><option value="Autre" @selected(old('specialty') === 'Autre')>Autre</option></select></div><div id="customSpecialtyWrapper" class="hidden"><label for="customSpecialty" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Précisez votre spécialité <span class="text-error">*</span></label><input id="customSpecialty" name="custom_specialty" maxlength="100" value="{{ old('custom_specialty') }}" placeholder="Ex. Oncologie" class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"></div></div>
    </section>
    <section class="space-y-5 border-b border-surface-variant pb-8">
        <div class="flex items-start gap-3"><span class="material-symbols-outlined mt-0.5 text-primary">contact_mail</span><div><h3 class="font-titre-sm text-titre-sm text-on-surface">Coordonnées</h3></div></div>
        <div class="grid grid-cols-1 gap-gouttiere sm:grid-cols-2"><div><label for="doctorEmail" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Email professionnel <span class="text-error">*</span></label><input id="doctorEmail" name="email" type="email" required maxlength="255" value="{{ old('email') }}" class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"></div><div><label for="doctorPhone" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Téléphone</label><input id="doctorPhone" name="phone" type="tel" maxlength="30" value="{{ old('phone') }}" class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"></div><div><label for="doctorPassword" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Mot de passe <span class="text-error">*</span></label><input id="doctorPassword" name="password" type="password" required minlength="8" autocomplete="new-password" class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"></div><div><label for="doctorPasswordConfirmation" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Confirmation <span class="text-error">*</span></label><input id="doctorPasswordConfirmation" name="password_confirmation" type="password" required minlength="8" autocomplete="new-password" class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"></div></div>
    </section>
    <label for="doctorConfirmation" class="flex cursor-pointer items-start gap-3 rounded-xl border border-outline-variant bg-surface-container-low p-4"><input id="doctorConfirmation" name="confirmation" required type="checkbox" class="mt-1 h-4 w-4 accent-primary"><span class="font-corps-sm text-corps-sm text-on-surface-variant">Je confirme l’exactitude de mes informations professionnelles. <span class="text-error">*</span></span></label>
    <button type="submit" class="flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-4 font-label-bold text-label-bold text-on-primary transition-colors hover:bg-primary-container">Créer mon profil médecin <span class="material-symbols-outlined">arrow_forward</span></button>
</form>
<script>
    (() => {
        const specialty = document.getElementById('doctorSpecialty');
        const customWrapper = document.getElementById('customSpecialtyWrapper');
        const customInput = document.getElementById('customSpecialty');
        if (!specialty || !customWrapper || !customInput) return;
        const updateCustomSpecialty = () => {
            const isCustom = specialty.value === 'Autre';
            customWrapper.classList.toggle('hidden', !isCustom);
            customInput.required = isCustom;
            customInput.disabled = !isCustom;
        };
        specialty.addEventListener('change', updateCustomSpecialty);
        updateCustomSpecialty();
    })();
</script>
