<form action="{{ route('register.service.store') }}" method="POST" class="space-y-8">
    @csrf
    <section class="space-y-5 border-b border-surface-variant pb-8">
        <div class="flex items-start gap-3"><span class="material-symbols-outlined mt-0.5 text-primary">domain</span><div><h3 class="font-titre-sm text-titre-sm text-on-surface">Identité du service</h3><p class="mt-1 font-corps-sm text-corps-sm text-on-surface-variant">Présentez le service et son établissement de rattachement.</p></div></div>
        <div class="grid grid-cols-1 gap-gouttiere sm:grid-cols-2">
            <div class="sm:col-span-2"><label for="serviceEstablishment" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Établissement <span class="text-error">*</span></label><select id="serviceEstablishment" name="id_etablissement" required class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"><option value="">Sélectionner votre établissement</option>@foreach ($etablissements as $etablissement)<option value="{{ $etablissement->id_etablissement }}" @selected(old('id_etablissement') === $etablissement->id_etablissement)>{{ $etablissement->nom_etablissement }}</option>@endforeach</select></div>
            <div><label for="serviceName" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Nom officiel du service <span class="text-error">*</span></label><input id="serviceName" name="service_name" required maxlength="100" value="{{ old('service_name') }}" placeholder="Ex. Cardiologie interventionnelle" class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"></div>
            <div><label for="serviceSpecialty" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Type de service <span class="text-error">*</span></label><select id="serviceSpecialty" name="specialty" required class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"><option value="">Sélectionner...</option><option value="Cardiologie" @selected(old('specialty') === 'Cardiologie')>Cardiologie</option><option value="Neurologie" @selected(old('specialty') === 'Neurologie')>Neurologie</option><option value="Urgences" @selected(old('specialty') === 'Urgences')>Urgences</option><option value="Laboratoire" @selected(old('specialty') === 'Laboratoire')>Laboratoire</option><option value="Autre" @selected(old('specialty') === 'Autre')>Autre</option></select></div>
        </div>
    </section>
    <section class="space-y-5 border-b border-surface-variant pb-8">
        <div class="flex items-start gap-3"><span class="material-symbols-outlined mt-0.5 text-primary">manage_accounts</span><div><h3 class="font-titre-sm text-titre-sm text-on-surface">Responsabilité du service</h3><p class="mt-1 font-corps-sm text-corps-sm text-on-surface-variant">Identifiez le responsable administratif du service.</p></div></div>
        <div class="grid grid-cols-1 gap-gouttiere sm:grid-cols-2"><div><label for="serviceHeadFirstName" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Prénom du responsable <span class="text-error">*</span></label><input id="serviceHeadFirstName" name="head_first_name" required maxlength="100" value="{{ old('head_first_name') }}" class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"></div><div><label for="serviceHeadLastName" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Nom du responsable <span class="text-error">*</span></label><input id="serviceHeadLastName" name="head_last_name" required maxlength="100" value="{{ old('head_last_name') }}" class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"></div></div>
    </section>
    <section class="space-y-5 border-b border-surface-variant pb-8">
        <div class="flex items-start gap-3"><span class="material-symbols-outlined mt-0.5 text-primary">lock</span><div><h3 class="font-titre-sm text-titre-sm text-on-surface">Coordonnées et sécurité</h3></div></div>
        <div class="grid grid-cols-1 gap-gouttiere sm:grid-cols-2"><div class="sm:col-span-2"><label for="serviceEmail" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Email institutionnel <span class="text-error">*</span></label><input id="serviceEmail" name="email" required maxlength="255" type="email" value="{{ old('email') }}" placeholder="nomservice@gmail.com" class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"></div><div class="sm:col-span-2"><label for="servicePhone" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Téléphone direct <span class="text-error">*</span></label><input id="servicePhone" name="phone" required maxlength="30" type="tel" value="{{ old('phone') }}" placeholder="01 23 45 67 89" class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"></div><div><label for="servicePassword" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Mot de passe <span class="text-error">*</span></label><input id="servicePassword" name="password" required minlength="8" autocomplete="new-password" type="password" class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"></div><div><label for="servicePasswordConfirmation" class="mb-unite-base block font-label-bold text-label-bold text-on-surface-variant">Confirmation <span class="text-error">*</span></label><input id="servicePasswordConfirmation" name="password_confirmation" required minlength="8" autocomplete="new-password" type="password" class="w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-4 py-3 text-on-surface"></div></div>
    </section>
    <label for="serviceConfirmation" class="flex cursor-pointer items-start gap-3 rounded-xl border border-outline-variant bg-surface-container-low p-4"><input id="serviceConfirmation" name="confirmation" required type="checkbox" class="mt-1 h-4 w-4 accent-primary"><span class="font-corps-sm text-corps-sm text-on-surface-variant">Je confirme l’exactitude des informations fournies. <span class="text-error">*</span></span></label>
    <button type="submit" class="flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-4 font-label-bold text-label-bold text-on-primary transition-colors hover:bg-primary-container">Créer le compte service <span class="material-symbols-outlined">arrow_forward</span></button>
</form>
